apiVersion: v1
data:
  mapRoles: |
    # Worker Node Role (existing)
    - rolearn: arn:aws:iam::344249396000:role/eksctl-myEKScluster-nodegroup-my-n-NodeInstanceRole-nUbfNQpwzK4C
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

    # CodeBuild Role (add this)
    - rolearn: arn:aws:iam::344249396000:role/codebuild-demo-eks-proj-service-role
      username: build
      groups:
        - system:masters
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"# Worker Node Role (existing)\n- rolearn: arn:aws:iam::344249396000:role/eksctl-myEKScluster-nodegroup-my-n-NodeInstanceRole-nUbfNQpwzK4C\n  username: system:node:{{EC2PrivateDNSName}}\n  groups:\n    - system:bootstrappers\n    - system:nodes\n\n# CodeBuild Role (add this)\n- rolearn: arn:aws:iam::344249396000:role/codebuild-eks-deploy-role\n  username: build\n  groups:\n    - system:masters\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"aws-auth","namespace":"kube-system"}}
  creationTimestamp: "2025-10-11T16:01:26Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "19717"
  uid: bb50d2de-8e2e-400e-a599-a7dd75a7a3b1
